{ pkgs }: {
  deps = [
    pkgs.chromium
    pkgs.chromedriver
    pkgs.nodePackages.puppeteer
    pkgs.nodePackages.puppeteer-extra
    pkgs.nodePackages.puppeteer-extra-plugin-stealth
    pkgs.nodejs_20
    pkgs.libnotify
    pkgs.libpng
    pkgs.libpng.dev
    pkgs.libwebp
    pkgs.fontconfig
    pkgs.fontconfig.dev
    pkgs.freetype
    pkgs.freetype.dev
    pkgs.stdenv.cc.cc.lib
    pkgs.xorg.libX11
    pkgs.xorg.libX11.dev
    pkgs.xorg.libXcomposite
    pkgs.xorg.libXcursor
    pkgs.xorg.libXdamage
    pkgs.xorg.libXext
    pkgs.xorg.libXfixes
    pkgs.xorg.libXi
    pkgs.xorg.libXrandr
    pkgs.xorg.libXrender
    pkgs.xorg.libxcb
    pkgs.xorg.libXScrnSaver
    pkgs.nss
    pkgs.nss.dev
    pkgs.nspr
    pkgs.nspr.dev
    pkgs.atk
    pkgs.atk.dev
    pkgs.at-spi2-atk
    pkgs.at-spi2-atk.dev
    pkgs.at-spi2-core
    pkgs.at-spi2-core.dev
    pkgs.cups
    pkgs.cups.dev
    pkgs.dbus
    pkgs.expat
    pkgs.expat.dev
    pkgs.gtk3
    pkgs.gtk3.dev
    pkgs.glib
    pkgs.glib.dev
    pkgs.pango
    pkgs.pango.dev
    pkgs.cairo
    pkgs.cairo.dev
    pkgs.alsa-lib
    pkgs.alsa-lib.dev
  ];
}